version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
      - mongoconfig:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=express
    networks:
      - app-network

  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: cliente
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/express-cliente
    networks:
      - app-network

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/express-service
    networks:
      - app-network

volumes:
  mongodb_data:
  mongoconfig:

networks:
  app-network:
